version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    hostname: bot_psql
    volumes:
      - ./database-scripts/init:/docker-entrypoint-initdb.d
    ports:
      - "6432:5432"
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge